version: '3.4'

services:
  db:
    image: postgres:14-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=ldwccoxa3
      - POSTGRES_USER=test
    volumes:
      - test-db:/var/lib/postgresql/data:rw
    ports:
      - target: 5432
        published: 5432
        protocol: tcp

volumes:
  test-db: {}